language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd src/
script:
  - ./make.sh
branches:
  only:
    - master
notifications:
  recipients:
    - michael.j.salerno@stonybrook.edu
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#roofis0"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
